services:
  db:
    image: postgres:latest
    container_name: kursy_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: KursyWalut123
      POSTGRES_DB: waluty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: kursy_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:AplikacjaWaluty123@db/waluty
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    container_name: kursy_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: